services:
  web:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - ./:/app/

  database:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_DB: '${DATABASE_NAME}'
      POSTGRES_USER: '${DATABASE_USER}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
