services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: go_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
